### ISSUE TITLE
Log in with phone

### ISSUE THREAD

**Issue by garette1** [Necrobot-Private/NecroBot#1036]
can i log in my account with phone? will i get banned.i was start on necrobot.i never logged in phone?

**Comment by Ryndael** [comment]
Questions like this are better answered on Discord.

However. Yes, you can log into your phone. Do not log in at the same time as the bot. You must also allow enough time to pass so that it's physically possible to travel to wherever your phone is. I.E. If you're botting at a location 10 minutes away, wait 10 minutes before logging into your phone.

**Comment by garette1** [comment]
@Ryndael if i turn off gps, i have to wait????

**Comment by Ryndael** [comment]
I would, to be safe. Your location can still be approximated by your network.
