### ISSUE TITLE
[Question] WalkbackDistanceLimit

### ISSUE THREAD

**Issue by wilsondgonzales** [Necrobot-Private/NecroBot#105]
@samuraitruong In regards to `"WalkbackDistanceLimit":` Just looking for some clarification. Is this for:

1) The bot walks back to start location after exceeding this limit
2) The distance the bot is allowed to walk back
3) Something entirely different?

Sorry for using the issues area

**Comment by samuraitruong** [comment]
because human walk will make the bot walk outside radius you define (1000).

let say after finish snipe, bot is 500m from closest pokestop. 
if you setup it is 350
bot will see that is no in range you setup, and you are too far, it will start farming from new location. in another way, if you setup it is 600. bot will walk back to that pokestop to continue farm. that logic apply for non GPX only.

**Comment by samuraitruong** [comment]
and actually, I thought radius limit is useless, we don't need it. I would remove it in the future. just make bot go to any where has pokemon and pokestop.

**Comment by huynhdtanh** [comment]
@samuraitruong : are you vietnamese ? and can u speak vietnamese ? sry for other questions

**Comment by bulubebek** [comment]
AFAIK necrobot's radius limit is calculated from last visited fort - not calculated from spawn coordinate in config.json. so basically, bot will keep moving as long as there is pokestops available and reachable.

**Comment by samuraitruong** [comment]
@huynhdtanh  : I was born in VN, live in VN 33 years . I guess I can speed Vietnamese very good

**Comment by samuraitruong** [comment]
@bulubebek  :  No, that wrong, Gym has it distance setting. If we set MaxDistance in GYM to 3000m, and Radius is 1000m, after gym it will look for another gym within 3km. if there no gym , it will walk back to farming zone. But, farming zone will change if Snipe change the farm zone before. that is complicated. 

I am happy even bot run some where, that good because it not create any pattern :)

**Comment by wilsondgonzales** [comment]
@samuraitruong thank you for the clarification. While I would prefer the bot to compare distance against the pokestop it last visited before it started the snipe journey, it is what it is. The reason I say this to because personally for me, it's nice to have control over the bot to stay within vicinity of water where dratinis spawn.
