### ISSUE TITLE
"bad authentication"

### ISSUE THREAD

**Issue by lorenzoL1** [Necrobot-Private/NecroBot#1064]
i can't login anymore .

google returned an error message ; badauthenaction.
i didn't change my password . 
or settings . its started when gen2 came in the game . 
can someone help me pleas

**Comment by hardknoxni69a** [comment]
gen 2 has been out for sometime now it doesnt have to do with bot double check your google settins allow less secure apps or make a app specific password but problem lies with google allowing it not the bot and def not because gen 2 sorry let us know in discord if you need help with google we should be able to help you track down right setting but just search my account google

**Comment by lorenzoL1** [comment]
ive changed my google settings from allow less secure apps : on .
but it's still not working

**Comment by hardknoxni69a** [comment]
please join our discord to get help fixing it unfortunately this is a google issue not necro better support will be in our chat

**Comment by hardknoxni69a** [comment]
have u tried making a password just for necro and allow it individually

**Comment by lorenzoL1** [comment]
don't know how to join and to set a individually password

**Comment by hardknoxni69a** [comment]
on main page is our dscord link you will love it but go into your google account page

**Comment by hardknoxni69a** [comment]
https://discord.gg/b93tZDb

**Comment by hardknoxni69a** [comment]
https://myaccount.google.com/?pli=1

**Comment by hardknoxni69a** [comment]
turn 2 step verification off and allow less secure apps
