### ISSUE TITLE
i keep and tranfer pokemon cp and iv

### ISSUE THREAD

**Issue by zsatanxz** [Necrobot-Private/NecroBot#110]
"PokemonConfig": {
    "KeepMinCp": 1250,
    "KeepMinIvPercentage": 10.0,
    "KeepMinLvl": 1,
    "KeepMinOperator": "and",
    "UseKeepMinLvl": true,
    "PrioritizeIvOverCp": false,
    "KeepMinDuplicatePokemon": 1,
    "UsePokemonToNotCatchFilter": true,
  },

**Comment by ttpro1995** [comment]
@zsatanxz , could you provide more detail about your problem ? Is it a bug or feature request or suggestion ?

**Comment by zsatanxz** [comment]
"KeepMinCp": 2000,
    "KeepMinIvPercentage": 90.0,
    "KeepMinLvl": 30,
    "KeepMinOperator": "and",
    "UseKeepMinLvl": true,
    "PrioritizeIvOverCp": true,
    "KeepMinDuplicatePokemon": 1,
    "UsePokemonToNotCatchFilter": true,
    "UsePokemonSniperFilterOnly": false,
    "DumpPokemonStats": false
tranfer pokemon
keep cp 1000 iv 90
tranfer cp 2000 iv 85

**Comment by zsatanxz** [comment]
![untitled](https://cloud.githubusercontent.com/assets/21266188/18476636/07afdb0c-79f5-11e6-9a4e-e3a87c3cdf29.jpg)

**Comment by ttpro1995** [comment]
As I see, 
`"KeepMinOperator": "and"`
mean pokemon only be keep if it satisfy all the condition 
CP > 2000 and IV > 90  and Level (level is not shown in your screenshot)

All pokemon in your screenshot got tranfer, even Kakuna with IV = 100, because they don't satisfy the condition CP >2000

I suggest change
`"KeepMinOperator": "and",`
to 
`"KeepMinOperator": "or"`
(meaning pokemon will be keep when one of those condition satisfy)

**Comment by zsatanxz** [comment]
it okay??

    "KeepMinCp": 2000,
    "KeepMinIvPercentage": 85.0,
    "KeepMinLvl": 25,
    "KeepMinOperator": "or",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": false,

**Comment by petpetpetvm** [comment]
@zsatanxz remember to close this when problem is solved

**Comment by CreativiTimothy** [comment]
Note that if you turn on "TransferWeakPokemon" to true, it will ignore all your options and just use the CP option, so your 100 IV Pokemon will be transferred, at least it was like that in the NoxxDev version
