### ISSUE TITLE
TROYAN?

### ISSUE THREAD

**Issue by cplcplcpl** [Necrobot-Private/NecroBot#1112]
Hi.
Karpesky antivirus detect: MSIL.Crypt.czkr 
¿?¿?

**Comment by samuraitruong** [comment]
hey, where did you download the file? 

You may download from unofficial site then they put virus in

**Comment by hubbalicious** [comment]
Same for me with Kaspersky. Downloaded from release page. Older version works fine, but after updating if I close/restart bot I get the same message and bot doesn't work. Have to revert back to old version and update again everytime I restart.

**Comment by hubbalicious** [comment]
Thought it might just be Kaspersky. Tried running the bot on my work pc and Symantec also doesn't like it.

**Comment by jjskuld** [comment]
Strange.. will take a look.

**Comment by hubbalicious** [comment]
Kaspersky getting aggressive. Immediately deletes the exe files after extracting, even on the older version now.

**Comment by mortifuri** [comment]
![image](https://cloud.githubusercontent.com/assets/26123714/23478776/c408e42e-fe98-11e6-9ebb-221adfdab4bd.png)

Kaspersky is now deleting the files for me as well.

**Comment by jjskuld** [comment]
Can you try the online scanner?  

I just went to https://scan.kaspersky.com and uploaded the NecroBot2.win.zip (which you should be downloading from https://github.com/Necrobot-Private/NecroBot/releases/download/v1.0.0.125/NecroBot2.WIN.zip).

It shows that there are no issues. 

<img width="783" alt="screen shot 2017-03-01 at 12 22 15 pm" src="https://cloud.githubusercontent.com/assets/16908714/23479658/083fbf88-fe7a-11e6-8fb0-d65ffd76f405.png">

**Comment by jjskuld** [comment]
Also not sure where you got that file from but we do not have any files called `necrobot2.win.exe.old` in our zip.

**Comment by mortifuri** [comment]
The .old file was from when the application tried to update itself. It tried to do the update but then crashed on coping the accounts.db file. Seen another issue created for this here as well. 

This copy of the bot had the .old files listed. 

The other copies didn't have the old files, but they were also delete from the computer for the same Trojan detection. 

If I run the older version, it updates and some of the files are auto deleted. So I think the issue is with how the program is doing the auto update and what files it is picking up that way.
But it is working again right now, and both online and desktop say no issues with the file. 

The only file I downloaded was the one that necrobot.net directed me to on the release page.

Also, Kaspersky did a definition update before this happened, and I forced another definition update before I tired the new download. The old download is now running as a non virus as well, though it did delete the GUI during the update process on it self. 

Best guess Kaspersky had a false positive they fixed.

**Comment by mortifuri** [comment]
Looks like Kaspersky decided it was a Trojan again.

**Comment by hubbalicious** [comment]
Yep...still a problem for me too. For now I created a folder "abc", added exclusion for abc\necrobot2.exe and abc\necrobot2.win.exe, then extract the necro zip to abc folder. Kaspersky still triggers when the bot updates and the .old file is generated, but leaves the regular files alone.

Don't think the devs can do anything about this. If this started because of a definition update, then probably going to keep happening...

**Comment by jjskuld** [comment]
"The only file I downloaded was the one that **necrobot.net** directed me to on the release page."

WAIT A SEC, WE DON'T OWN NECROBOT.NET!!!  Looks like some guy put up a site to profit from our work.

Hmm.. the download page is still redirecting to our Github site. Still it's strange that Kaspersky things this is a trojan.  Let me investigate further to see what's going on.

**Comment by Shaglakh** [comment]
Kaspersky getting aggressive. Immediately deletes the exe files after extracting,

**Comment by jjskuld** [comment]
@shaglakh @mortifuri @hubbalicious Can anyone of you guys try the online Kaspersky scanner and let me know if the online scan shows the file as clean or as being flagged/

**Comment by mortifuri** [comment]
Desktop Scanner right after I extract the files:

![image](https://cloud.githubusercontent.com/assets/26123714/23531732/49c80064-ff7e-11e6-8833-52bb71913add.png)

Same zip file uploaded to https://scan.kaspersky.com/Home/Result

![image](https://cloud.githubusercontent.com/assets/26123714/23531758/79a6b294-ff7e-11e6-96d1-6ece9fd980a2.png)
![image](https://cloud.githubusercontent.com/assets/26123714/23531765/7fcf08e2-ff7e-11e6-9ae4-bdad16533477.png)


Downloaded the latest release from the release page:
https://github.com/Necrobot-Private/NecroBot/releases/tag/v1.0.0.127

Desktop scanner after extraction:
![image](https://cloud.githubusercontent.com/assets/26123714/23531835/c9f6c16c-ff7e-11e6-8d16-4d1b1146a681.png)

Uploaded to kaspersky online:
![image](https://cloud.githubusercontent.com/assets/26123714/23531906/3430e332-ff7f-11e6-9cf4-4baefebf1b18.png)
![image](https://cloud.githubusercontent.com/assets/26123714/23531919/393f087c-ff7f-11e6-9bc9-7cf8d6e9ba2e.png)

**Comment by jjskuld** [comment]
OK guys, I have a suspicion about what is going on.  When the build is initially done, the file scan is clean.  So someone is overwriting the release with one with a trojan.  I have some ideas as how this is happening.  Stay tuned!

**Comment by hubbalicious** [comment]
Fkkkk...so I've been excluding and running malware on my machine? Please keep us posted and let us know what you find.

**Comment by Shaglakh** [comment]
With me is exactly the same message from Kaspersky as with, "mortifuri"

**Comment by SoccerCore11** [comment]
VirusTotal.com to upload files and scan for viruses
Instructions on how to remove Trojan.MSIL:  https://malwaretips.com/blogs/trojan-msil-removal/

**Comment by jjskuld** [comment]
We have secured our builds now so this should no longer happen in the future. I will leave this issue open for now.

**Comment by mortifuri** [comment]
New downloads are showing clean now. Thank you!

**Comment by hubbalicious** [comment]
FYI, Kaspersky still doesn't like Necrobot2.exe in the 131 release...Necrobot2.WIN seems fine. Other scans look clean though...only Kaspersky flags it.

**Comment by mortifuri** [comment]
Kaspersky just deleted the file again for me as well, and the online scan is still reporting the necrobot2.exe as a Trojan sadly.

**Comment by cplcplcpl** [comment]
Thanks for you job guys!! Yesterday ran OK!! Today is outher problem ;-)

**Comment by Shaglakh** [comment]
New downloads are not clean, again the message from kaspersky ther is trojan

**Comment by hardknoxni69a** [comment]
only applies to the 32bit version which all has been removed it goes up clean and after about 24hours someone overwrites the files so 32bit is being suspended for now until we resolve this issues thank you

**Comment by hardknoxni69a** [comment]
all set files been double checked SHA256 are confirmed
