### ISSUE TITLE
Pokemon Not Transferring

### ISSUE THREAD

**Issue by stayupthetree** [Necrobot-Private/NecroBot#1117]
I just get this over and over and over. I can manually transfer, but it doesn't seem to auto transfer.

http://prntscr.com/eeqz6o

**Comment by jjskuld** [comment]
What do your transfer filters look like?

**Comment by stayupthetree** [comment]
Default

**Comment by elmoo568** [comment]
I have the same problem.  It used to work great but started noticing this a few days ago.  Are there any new flags to check?  I was wondering if I'm missing any flags from any of the updates, so I manually did a diff between mine and one of OrdsonX's safe configs and don't see anything missing.  Anyone else having this problem?

**Comment by stayupthetree** [comment]
Does that safe config work? Where can I obtain it?

**Comment by elmoo568** [comment]
There are a few by OrdsonX in the discord chat under share_config discussions. I didn't use the config, I just used it to compare with mine to see if there's anything missing that might be preventing the pokemon transfer.  Have you tried going into the chat?  Pretty cool discussions going on in there.

**Comment by hardknoxni69a** [comment]
Ya you have to set up your transfer settings in the Pokemon config section for global then your transfer filters if u want to set certain Pokemon individually I recommend taking the time.and go over every line of config as you can be missing out on a ton of amazing features because once u set everything correctly you can literally run bot without looking at it and u won't have to worry about anything but ya join our discord for basic questions as there are always people there such as myself always happy to help
