### ISSUE TITLE
SnipeLocationServer doesn't work in latest update

### ISSUE THREAD

**Issue by LSAC-Hao** [Necrobot-Private/NecroBot#1149]
Following configuration no longer works. NECrobot2 not longer talk to my locahost:12345 port. Therefor not connection from my location coords script to Necrobot2 was established. 

  "SnipeConfig": {
    "UseSnipeLocationServer": true,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 12345,

**Comment by samuraitruong** [comment]
I did removed this part since the main project pogolocationfeeder has dead for long time

**Comment by LSAC-Hao** [comment]
If you removed SnipeLocationServer, what is your recommendation to feed my own coords into NECROBOT2?

**Comment by samuraitruong** [comment]
where did you get coord? from discord?

**Comment by LSAC-Hao** [comment]
No, I used node.js and parsed a few Pokémon map websites.

**Comment by samuraitruong** [comment]
yeah, I will bring it back for u, can you share me list website you have coord. I may add them to main internal snipe feed

**Comment by LSAC-Hao** [comment]
Can I inject then into NECROBOB2 via websocket? What does websocket settings do?

**Comment by LSAC-Hao** [comment]
Sure thing, I will check in my scripts into GitHub and send you a link.

**Comment by samuraitruong** [comment]
well, the old snipe method only check for pokemon name, it is super poor function compare to the huge snipe data and features we currently has. it surprised me why you want to use this snipe because I don't want people ask why It not snipe pokemon in PokemonToSnipeList, or why it snipe more, because now everything are in PokemonSNipefilter with can use with level, cp, moves, verify, candy, pokedex..... which is 10 times compare to old snipe method? If I bring it back, people will confused in config again.

**Comment by LSAC-Hao** [comment]
Then you shouldn't bring it back. What I was asking is that is there any interfaces 3rd party developers can inject their own coordinates into the system?

**Comment by samuraitruong** [comment]
you can change datasharing url to your socket. I may if you code with nodejs, using socketio is same interface with my data server. then it should work

**Comment by LSAC-Hao** [comment]
Great! I'll give it a try and report back. Thanks!

**Comment by samuraitruong** [comment]
I still revert it back but not revert config setting

**Comment by LSAC-Hao** [comment]
Thanks!

**Comment by samuraitruong** [comment]
you have to use snipepokemonfilters to use with old snipe method.
