### ISSUE TITLE
Ignore AuthConfig when Multibot is set to True

### ISSUE THREAD

**Issue by spawnscanner** [Necrobot-Private/NecroBot#1161]
### Expected Behavior:
When:
  "AllowMultipleBot": true,

  "AuthConfig": {}
should be ignored and this error should not happen
"(ERROR) You need to fill out Username and Password in auth.json!"

### Actual Behavior:
On rare switch for multibot and when the bot reaches the bottom of the account list.
The bot will try to switch to an account with no info.

Version:
Windows Version: 10

**Comment by hardknoxni69a** [comment]
attach auth please void whats important

**Comment by OrdsonX** [comment]
![as](https://cloud.githubusercontent.com/assets/26216244/23601756/ff56802c-0244-11e7-8283-1978c1368fe5.jpg)
[auth.txt](https://github.com/Necrobot-Private/NecroBot/files/820482/auth.txt)

**Comment by samuraitruong** [comment]
we don't need ignore this, add 1 more account in here, because the code already use this as 1st acc

**Comment by spawnscanner** [comment]
That's obviously not the logical way that should work. This solution is just a band-aid on a real problem.

**Comment by jjskuld** [comment]
Working on a real fix...

**Comment by spawnscanner** [comment]
That's good to know, just wish issues weren't closed if they haven't actually been resolved?

**Comment by hardknoxni69a** [comment]
I think truong closed because when u have 1 account it should be false for
multibot and you won't get this issue or if auth is filled out completely
you wont get issue and as you can see when an issue is closed doesn't mean
we just ignore it @jj still came in. closed just means it not a severe
issue but once a dev comments we get notifed of all.activity in the thread
we are not gonna forget about the issue and if it is more severe it will
get reopened we are here to help the best we can
