### ISSUE TITLE
Request: Add Buddy Pokemon Support

### ISSUE THREAD

**Issue by gjimenezf** [Necrobot-Private/NecroBot#130]
Please Add support for buddy pokemon

**Comment by ValorRed** [comment]
Let's wait for API update, better add this after resolved the SafetyNet response emulation.

**Comment by ajns73** [comment]
I saw a car today with huge rims on it. I asked the guy how much they were. He proudly replied that it cost him $1000 a wheel. I asked him how much he paid for the car and he very quietly said , "$3900 used."

**Comment by ValorRed** [comment]
Already progress on iOS
https://www.reddit.com/r/pokemongodev/comments/52mvep/xcon_successfully_bypasses_ios_jailbreak/?st=it2bw4o2&sh=635b7298

This pretty much proved my suspicion on there is not much changes in API side. Pass a sudo response to the server shall be easy. But it's not very easy for the game running on Android rooted devices.

**Comment by Silph-Road** [comment]
.37 API is not available for use in bot.... when it is buddy will be added.

**Comment by Prolesious** [comment]
Can this be looked at now?  As I have one setup and apparently it meets the criteria  for transfer, but it can't since it's buddy, but the script keeps trying anyways.  

Making it aware, it could  collect the candy and maybe some logic to pick buddies based on candies needed to evolve a certain pokemon!
