### ISSUE TITLE
GUI Does not start after Update 

### ISSUE THREAD

**Issue by Buckrogers81** [Necrobot-Private/NecroBot#1305]
The GUI of the Necrobot2Win does not start after the Last update, The Console opens and I am asked to : 

Rebuild the transaction folder YN

but what ever I do, it will not continiu. And dont tell me to press Y and Enter. I have tried >/(

I can still run the Bot from the necrobot2.exe console

**Comment by gitnotoff** [comment]
just open the console with this button:
![image](https://cloud.githubusercontent.com/assets/26252312/24038740/00912dfe-0b03-11e7-94d7-d282a7ae155a.png)

then you can use " Y and Enter "

But the question : Rebuild the transaction folder YN  is strange.

**Comment by michx85** [comment]
Pressing "Y" will not solve the Problem. Necrobot will ask you immediately again.

There is a problem with the key "ho-oh" in the german translation file. => Config\Translations\translation.de.json
Don't know if other languages are also involved.

If you change  the key in line 1590 form "ho-oh" to "hooh"  it works without error message.
But it's only a workaround...

**Comment by hardknoxni69a** [comment]
It's not really a workaround it's because the bot is trying to translate something that isnt in its database by inputting correctly the issue goes away. People need to realize that the schema files that comes with the config are like a roadmap showing you what's acceptable and spelling makes things alot easier to learn and understand but unfortunately no one goes over it to correct there errors
