### ISSUE TITLE
BUG in translation.de.json

### ISSUE THREAD

**Issue by mboeder** [Necrobot-Private/NecroBot#1388]
Could someone please fix issue with this translation file. After each upgrade Bot does not start because of issue with the file. The value "ho-Oh" is causing the the error. When is update it to "hoOh" the bot continues without problems

**Comment by Experte9** [comment]
have the same problem, but not really solved #1384 ...

**Comment by hardknoxni69a** [comment]
please read the info while creating an issue before making one it says to check issues and this has been spoken of multiple times

**Comment by mboeder** [comment]
@hardknoxni69a Please apologize if i did something incorrect. I know it was discussed before and i know how to fix it manual. I don´t have any coding skills, but i thought it should be easy to correct the file on download server. With auto update = true the translation file will always be replaced with non working values.

**Comment by hardknoxni69a** [comment]
It's not really an issue with translation though because once u update your main config.json to hoOh you will never see the issue again. Alot of people don't realize that the schema file that is included is basically a master guide for all.acceptables spellings and types of values needed. So if ur ever looking how to spell a Pokemon or move just check out your schema guide. We have had this same question on here multiple times so gets ridiculous when the people don't use the search function when theyre question has been answered numerous times. Check out schema though when it comes to config file it is a big help
