### ISSUE TITLE
v.151

### ISSUE THREAD

**Issue by Polytoxic75** [Necrobot-Private/NecroBot#1437]
what´s the point in a new version that still won´t work.148 is over again too ): respect to the developers but when theres a new vs I hope it may work again and then feel even more fooled because it did nothing.

**Comment by cj3n** [comment]
It was working until go forced 0.61 the past 3 hours ago. That's why it's not working now, so that's why. You won't be able to bot until it's updated to 0.61 api. I was using .151 all day until my go updated on my phone and the bot stopped working at the same time. I'm sure it be updated soon, so be patient. There's nothing to redo you will have to wait, their pretty quick about it.. Lol .148 won't work I bet ya.

**Comment by CaptainAdaquit** [comment]
yeah, it worked for a solid day before 0.61 was mandated just a few hours ago.  Kind of hard to bitch about people working for free so you can cheat.  :P

**Comment by V1R4G3** [comment]
No need to get condescending toward someone who is frustrated with situation.

**Comment by CaptainAdaquit** [comment]
hm, I really didn't mean it that way.  I guess it depends on how it's read.  I'm sorry if it came across as condescending.

**Comment by hardknoxni69a** [comment]
lol feel free to contribute by making a fork and requesting pull requests we are always looking for devs

**Comment by Polytoxic75** [comment]
Didn't intend to bitch at someone. All my respect to you guys for making things like necrobot possible for us. Maybe I just used some wrong language leaving space to be misunderstood

Geri's IPhone
