### ISSUE TITLE
config

### ISSUE THREAD

**Issue by unknowkir** [Necrobot-Private/NecroBot#1561]
do any of you guys know good config for fast leveling ?

**Comment by V1R4G3** [comment]
The default one is pretty good.

**Comment by KyoshoSon** [comment]
At least for me the default config didn't evolve the usual Pidgey, Weedle, etc in the way to maximize XP gain. I end up with tons of candies for those weak pokemons. Looks like for me the default config batch transfer those instead of evolve them.
I had to customize some of the evolve functions so all my pidgey, weedle, caterpie, natu, hoothoot, etc. get evolved then transferred. My goal was to build a high level account with 3200+ CP dragonite, tyranitar and blissey to dominate local gyms. Your goal may be different.

**Comment by redking974** [comment]
It's not an issue. Please close it and ask your question into Discord server. Regards.
