### ISSUE TITLE
Account had been flagged

### ISSUE THREAD

**Issue by illusion021092** [Necrobot-Private/NecroBot#1686]
I am using Necrobot latest release with pokefarmer hash key.
But it still flag my both account at level 22 and level 20.
Is there anything i am doing wrong.
FYI - I am not using sniper on my account.

This is my config file.
[config.txt](https://github.com/Necrobot-Private/NecroBot/files/991133/config.txt)

**Comment by LimitedOC** [comment]
i didnt watch ur config cuz i have no time but i can say that u can get flagged if you do some things that u must not. you have to take care of the walking speed, distances, human walk (not flying like crazy) stop the autosnipe because sniper is dead. limit of the pokemons and pokestops at 24 hours. im also flagged but not because of the bot. i did a great distance from my house to the airport (2 hours distance) and i got flagged because i logged in there. im 37 lvl so you have to be careful. also you need to put the bot at your area. i live in greece and until 33lvl i went to new york and i was like 1 captca per minute or 30 mins. (and flagged. but flag gets remove after some weeks). but i didnt need to do this because sniper worked well. i have 12k dratini candies because sniper caught everything. you will also need to take care of the catch stuff. dont make it catch them perfect with no falses. thats what i can think right now! you may have do nothing from above i just say. it will might help

**Comment by illusion021092** [comment]
Can you share your config with me
@LimitedOC

**Comment by LimitedOC** [comment]
its the basic one, you can just re-download the bot put ur key inside and you will be fine

**Comment by akashgupta9990** [comment]
I haven't changed anything in the existing config except for my location & setting snipe as false.
Can i continue botting with flagged account. How long i can bot with flagged account.

**Comment by cjhart** [comment]
My account was flagged for 2 weeks - I just stopped botting and the msg went.

However see issue: #1649

**Comment by Lord-Haji** [comment]
GitHub is only for bug reports and feature suggestions no support use discord for that
