### ISSUE TITLE
[Feature Request] Disable killswitch so it does not prompt

### ISSUE THREAD

**Issue by vfuyong** [Necrobot-Private/NecroBot#183]
As title says. This is important as I have some other script to automate the bot. Potentially it can be made as a config item?

Thanks.

**Comment by Silph-Road** [comment]
The killswitch has to stay on to protect ppl who don't read the issues page and might bot on a "valuable" account and end up getting a good account banned, so many problems this week due to .35 being forced and the bot is not 100% safe right now.

Use this: https://github.com/Necrobot-Private/NecroBot/wiki/Command-Line-Arguments

**Comment by hardknoxni69a** [comment]
Just add the " -killswitch="false"" to your script so run necrobot.exe -killswitch="false" and it will override killswitch as silph kindly suggester
