### ISSUE TITLE
Snipe not working

### ISSUE THREAD

**Issue by Polytoxic75** [Necrobot-Private/NecroBot#1875]
The Snipe function is not working for me at all. when I click on the Snipe-Tab no Pokemon are shown ever.

**Comment by TheWizard1328** [comment]
Sniping has been down for a while now due to an API change by Niantic. Warnings and all kinds of bans have been happening if you activate auto snipe or turn on snipe scanner. Use at own risk. Even using a smart teleporting system could get warnings, bans or slashed Pokemon. 

_Sent from my Samsung SM-N920W8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
