### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by mzamza20** [Necrobot-Private/NecroBot#1960]
[23:16:23] () Do you want to override killswitch to bot at your own risk? Y/N
[23:16:33] () Overriding Killswitch... you have been warned!
[23:16:35] () Key: 7N8HXXXXXXXXXXXX5C1V RPM: 150 Expiration Date: 8/29/2017 (5 Days 13 Hours 25 Minutes)
[23:16:35] (訊息) Websocket listening on at  wss://localhost:14251 or ws://localhost:14252

**Comment by Furtif** [comment]
normal @mzamza20 bot is disabled

**Comment by dimitris63** [comment]
i am sorry for not understanding. does that mean that necrobot  is down. Do you know what happened

**Comment by Furtif** [comment]
Is down temporary.

**Comment by dimitris63** [comment]
Thanks for the 411. How can I find out when it is back up

**Comment by dimitris63** [comment]
Is it still down. I am still getting the killswitch error. My account got banned because of this error message

From: J M
Sent: Friday, August 25, 2017 4:36 AM
To: Necrobot-Private/NecroBot <reply@reply.github.com>
Subject: RE: [Necrobot-Private/NecroBot] Unable to start (#1960)

Thanks for the 411. How can I find out when it is back up

**Comment by dimitris63** [comment]
@Lord-Haji we have not had a release for 24 days. Can we get an updated release that also takes care of the kill switch error

**Comment by blackms** [comment]
There is a problem with the API Implementation it's not related to NecroBot, god stop write idiot things. If you bot you get banned, that's all.
