### ISSUE TITLE
Cant get the bot running

### ISSUE THREAD

**Issue by Buckrogers81** [Necrobot-Private/NecroBot#2006]
Hi,
I just downloadet the latest Version 1.0.0.380
How the hell do I get that running? I am not a Developer, so I am just used to doubleklick a .exe and go configure the bot. But I dont find me way around. How do I Start?

Greetings

**Comment by RuthlessRuler** [comment]
hey bud,
what have you downloaded is source code, and since the bot is not using the latest api, as there was new update i dont recommend downloading it. Download the builds from https://github.com/Necrobot-Private/NecroBot/releases and find which says console, Gui, Win and stuff like that no source code, as you see the latest version is in source code, so you have to probably  compile it and run. So i recommend use other BOTS and make sure you have a Hash Key.

**Comment by Buckrogers81** [comment]
Thanks, that looks much better

**Comment by Buckrogers81** [comment]
But it just looks better. It still does not work. I can run the exe but the bot will freeze [19:01:07] () Console Layout is now 'Default'
I did use the Bot until version 185 so I am actually a bit familiar with it. I do have a Key

**Comment by Lord-Haji** [comment]
Download bot from releases section of GitHub, new version coming up soon

**Comment by Lord-Haji** [comment]
The development will be speeded up shortly in a few days when my winter vacations start

**Comment by RuthlessRuler** [comment]
ohh, i wil sure be waiting! This is still the best open source bots available till date!
