### ISSUE TITLE
[Feature Request] Force Raspberry usage over IV / CP

### ISSUE THREAD

**Issue by CreativiTimothy** [Necrobot-Private/NecroBot#230]
So recently, a 94% IV Zen Headbutt / Hyper Beam Snorlax ran away from me, even on an excellent throw D:
So the feature request I'm asking is to use berries over a certain IV/CP, just like how you can set over cp/iv for great balls, ultra balls, great throws, and excellent throws. Berries give a 1.5x catch rate, which is a big difference. Here's an example:

"UseBerryAboveCP":
"UseBerryAboveIV":

**Comment by hardknoxni69a** [comment]
ok @CreativiTimothy i just backed you up on other post but please review your config settings before making issues because this feature has been implemented for a very long time but ill tell you how it works to help you out

    "UseBerriesMinCp": 1000,
    "UseBerriesMinIv": 90.0,
    "UseBerriesBelowCatchProbability": 0.2,
    "UseBerriesOperator": "or",
    "MaxBerriesToUsePerPokemon": 2,

so this says that it will use a berry for any pokemon above 90IV or over 1000CP or has a catch rate below .2 and this is stock setting so your berry would have been thrown if you had berries available now the operator "or" means as long as any of those values are meant that a berry will be thrown if yours says and then it means all three values must be met in order for a berry to be thrown my settings will allow a berry to be thrown 2 times before just using pokeballs please review your personal settings and familiarize yourself because config settings are the most important aspect of the bot so please take in account all the features we have and be realistic with your settings if you want to be safe 

Please Close This Issue

**Comment by CreativiTimothy** [comment]
@hardknoxni69a Oh! Thanks! Sorry, I just couldn't find it in the config. I thought those config options would be near the other ones, but it's actually about 25 lines up. Thanks guys!
