### ISSUE TITLE
[Advanced Feature Request] KeepMinMoveWithCP: true/false

### ISSUE THREAD

**Issue by CreativiTimothy** [Necrobot-Private/NecroBot#242]
As a hardcore strategy player, I find a few cases where I want to keep a Pokemon when it has a moveset AND is above CP, OR above IV. There is currently no possible way to do this. For example, Jigglypuff, Pound + Body Slam is better than Wigglytuff at building prestige against a Snorlax. However, cp 10 Jigglypuff Pound + Body Slam is kinda useless without using a ton of Stardust. So I want a Jigglypuff that meets both CP and moveset requirements, OR if it has good IVs like 95+. Example:

```

    "Jigglypuff": {
      "KeepMinCp": 500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinLvl": 25,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "or",
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        [
          "poundFast",
          "bodySlam"
        ]
      ],
      "DeprecatedMoves": [],
      "MovesOperator": "or"
      **"KeepMinMoveWithCP": true**
    },
```

**"KeepMinMoveWithCP": true** should override the "KeepMinOperator" setting. In other words,
if ([aboveCP && Moves = true] or [aboveIV = true]), then keep

CP 350, IV 50, Pound + Body Slam -> transferred
CP 600, IV 50, Feint Attack + Dazzling Gleam -> transferred
CP 534, IV 50, Pound + Body Slam -> keep
CP 10, IV 96, Feint Attack + Dazzling Gleam -> keep

Because only advanced hardcore players will care about this setting, I suggest fixing other bugs and implementing other feature requests before this

**Comment by PenzRules** [comment]
This is worth to think about, but your assumptions are incorrect.
It will NOT keep the CP 10, IV 96, Feint Attack + Dazzling Gleam one because none of the moves is present. But, that sounds even better. Or am I wrong?
The other thing is you may want the MovesOperator set to "and" but I'm not sure if it means "move or move" or "(cp,iv) or (moves)". I know there is a readme, but don't know where.

**Comment by CreativiTimothy** [comment]
@PenzRules Well, I'm saying theoretically it should keep it. It's a feature request, not how it currently works. I'd like to keep my 96 IV Jigglypuff so I can evolve it into Wigglytuff. The ones with Pound + Body Slam I'd like to keep if it's high enough CP. If I set it to and, I think it gets more confusing because it must meet both the IV and moveset requirements

**Comment by PenzRules** [comment]
You're right, this wholy system could be better.
You might want a Snorlax with high defense and poundFast and another with high attack and lickFast. And while the Snorlax with pound should have bodySlam, the other one should have hyperbeam. Also both could have earthquake.
It would be easier to config if we could put a setup of all requirements in a single comma separated line, followed by the next line with another setup. this operator-options with "and / or" I just find confusing and limiting.
Additionally for the bubblestrategy there should be MaxCP, too.
And when it comes to MaxIV, it should be MaxAttack, MaxDefense and MaxStamina instead.
The same goes for MinIV.
And before we forgot, the MinLevel and MaxLevel should also be part of this single-line-setups.
To avoid messing up with UseMaxAttackIV and so on all this values must be preset with -1 so if we just don't set them they will not be used. Finally, KeepMinDuplicatePokemon must be part of every single-line-setup rather than using contingents.

How the config part looks now:
    "Snorlax": {
      "KeepMinCp": 1700,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 12,
      "Moves": [
        [
          "lickFast",
          "hyperBeam"
        ]
      ],
      "DeprecatedMoves": null,
      "KeepMinOperator": "or",
      "MovesOperator": "and"
    },

Oh, I see the second set of [], so it is already possible to specify multiple movesets?

How the config should look like:
    "Snorlax": {
        [
          "KeepMinCp": 0, "KeepMaxCP: -1", "KeepMinLvl": 25, "KeepMinAttackIV": 15, "KeepMinDefenseIV": 12, "KeepMinStaminaIV": 12, "KeepMaxAttackIV": -1, "KeepMaxDefenseIV": -1, "KeepMaxStaminaIV": -1, 80.0, "Moves": [["lickFast","hyperBeam"]["lickFast","eartquake"]], "KeepMinDuplicatePokemon": 2
        ][
          "KeepMinCp": 0, "KeepMaxCP: -1", "KeepMinLvl": 25, "KeepMinAttackIV": 12, "KeepMinDefenseIV": 15, "KeepMinStaminaIV": 12, "KeepMaxAttackIV": -1, "KeepMaxDefenseIV": -1, "KeepMaxStaminaIV": -1, 80.0, "Moves": [["poundFast","bodySlam"]["poundFast","eartquake"]], "KeepMinDuplicatePokemon": 10
        ]
    },

Well, I tried deleting the "returns" to make it easier to scroll down but the bot puts everything back in separated lines.

I'm not even sure if it is already possible to put multiple "Snorlax": {...} setups in the config.
If it is possible please tell us so. It would mean that Timothy's wishes were also met.
No, wait, it can't be possible by now because the first setup would transfer the snorlax's that could meet the other setups.
