### ISSUE TITLE
YOU GUYS FUCKED THİS NECROBOT DONT İMPROVE MORE

### ISSUE THREAD

**Issue by mucro9** [Necrobot-Private/NecroBot#252]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you searched to see if there are other Open/Closed issues for the same issue? If so, comment on that issue instead.
2. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/7FWyWVp 
4. Always confirm that your issue is reproducible, with the config you provide below.

### Your config.json:
```
replace this text with the contents of your config.json

```

### (OPTIONAL) Your Log:
```
replace this text with only the "relative" portion of your log. (Remove unnessary lines)

```

### Other Information
(Attach zip files if needed.)

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by CreativiTimothy** [comment]
Wtf is this?

**Comment by jjskuld** [comment]
@mucro9 Wow so salty...

**Comment by mucro9** [comment]
noobs dont make anything more..go kiss NoxxDevv ass

**Comment by vfuyong** [comment]
OP words might be too harsh but the idea I tend to agree. There are too many changes, the project can easily go unmanageable/un-testable. I am not afraid to say I am still on 0.9.7. There were many releases since then, and every release comes with different problems, existing features are also affected by each release. If you guys are in software engineering, code has to be tested well before releasing. If I can spot serious issue within the first 5 minutes, that is terribly wrong. 

And, most importantly, do not accept ALL feature requests simply because not all are constructive, and some can introduce significant risk (increasing bugs). 

Please carefully evaluate the current state of the project.

**Comment by CreativiTimothy** [comment]
@vfuyong Could you give an example please?

One example I know is how the lure Pokemon and renaming IV got messed up in the older versions of NecroBot2. There were none of those bugs in the NoxxDev bot. Other than that, the bot is fine for me.

**Comment by jjskuld** [comment]
@vfuyong I don't disagree with you that the code is quite often changing rapidly.  I think in a normal software engineering company, you'd have smoke tests or unit tests to make sure none of the previous functionality is broken.  However, this is not as easy to do with the bot.

Some of the large changes were to Rocket API, which was previously not maintained.  These changes have a large potential to break things, but changes were necessary in order to properly emulate a 0.35 client.  **If you are still on 0.9.7 I HIGHLY suggest upgrading to the latest version because the old versions are NOT emulating 0.35.  You may already be flagged for using a 0.33 client when they are already forcing upgrades from 0.33 clients.**

With regards to the pace of development, I myself prefer rapid iterations and releases.  To satisfy everyone, I think the best solution going forward is to have 2 release branches:

1) Stable branch - Well tested and known to be stable.  Most users will use this.
2) Alpha branch - Cutting edge branch with new features and changes.  Builds will not be promoted to stable branch until after more testing.

**Comment by hardknoxni69a** [comment]
Each of the updates are to make it better for everyone, the issues and requests are actually being implemented. The good thing thing is you DO NOT have to update. DO NOT complain this is open source so everyone has the opportunity to edit what you want. These devs are working non stop to make the best possible bot. I absolutely love getting updates a couple times a day sometimes by the time i notice a bug the next update has already fixed it. Every release has the changelog if you do not like do not download SUPPORT SUPPORT SUPPORT. Find another bot if YOU are not happy but I will be happier than ever with these updates rolling in. These devs spend there precious time appeasing us the last thing you should do is complain, maybe a polite bug request but never complain. These are people working for FREEEE!!! People that complain are the reason these bots close open source and charge money. They are sick of the B!TCHING. SUPPORT SUPPORT SUPPORT YOUR DEVS!!!!

**Comment by Silph-Road** [comment]
The thing is....
Even if we release a beta or alpha build.
People will still complain or point out issues the exact same way they do right now.
<br>
The key is to use a version that "works" for "your needs".
If something breaks in the new release, post an issue, outline the problem, and wait for a fix.
(Most major issues are resolved within 24 hours anyway.)
**Continue to use the version that "works" to your expectation.**
```
  "UpdateConfig": {
    "CheckForUpdates": false,
    "AutoUpdate": false,
```
<br>
No one forces you to update or try new features. 
As posted above, there is an option to turn on/off AutoUpdate.
<br>
Remember:
This "project" is **NOT** a software development firm that serves its customers.
The bot is for testing and development. That's why we don't allow it to be shared publicly, we don't need the attention.
Updates are pushed at a fast pace and that is a **GREAT** thing.

<br>
Lastly,
If any one thinks that the bot is "fucked up" now compared to before, feel free to delete it and move on....
