### ISSUE TITLE
Feature Suggestion: Walk direction, consider pokestops with Lure

### ISSUE THREAD

**Issue by ValorRed** [Necrobot-Private/NecroBot#267]
If this can be implemented, it will be much efficient to level up and more human like.
GoogleWalk or not, when not using GPX, bot is relatively randomly picking a direction to walk to. Can it find the direction with most stops having lure? Walk over, stay around the lured stop for a while before moving away, or move back and forth between several nearby stops with lure. Then, move away to another direction after a period of time, or lure is expired.

**Comment by CreativiTimothy** [comment]
This sounds nice, but a little difficult to implement. If it is implemented, let's make it optional

PriotizeStopsWithLures: true/false

The reason why is if it just stays a lured stop, it won't hatch eggs at all, so that's why I think this should be optional

**Comment by ValorRed** [comment]
If the avatar walk around the stop, it  shall still hatch the eggs, right? Because it can see any new lured pokemon even it is a little away from the stop.

Also, I was thinking have a setting to specify how long you stay around a lureing stop. User can specify 60 seconds each or walk to another nearby lureing stop and immediately coming back.

**Comment by samuraitruong** [comment]
people come to pured pokestop for catch pokemon, out bot has implent to void catch pokemon it mean we have too many pokemon already. why we need to come to lured and wait for 2-3 min to catch lured pokemon. this is not bring any benefit since
- msniper work very well to give you 100 rare pokemon a day
- hmw give you any kind of pokemon around
- lured pokemon is take 3 min to appear. if you stay 3 min is just waste time

**Comment by ValorRed** [comment]
What is hmw?
