### ISSUE TITLE
Automatic Update Error

### ISSUE THREAD

**Issue by CyberLykan** [Necrobot-Private/NecroBot#311]
Running a Microsoft Surface Pro 4 on Windows 10. It appears that the bot process itself is preventing the update, which I find pretty humiliating.

> Unhandled Exception: System.IO.IOException: The process cannot access the file 'C:\Users\ANameYouDoNotNeedToKnow\Desktop\My Stuff\NecroBot2\config\config.schema.json' because it is being used by another process.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
>    at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
>    at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
>    at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
>    at PoGo.NecroBot.Logic.Model.Settings.GlobalSettings.Save(String fullPath, Boolean validate) in c:\projects\necrobot2\PoGo.NecroBot.Logic\Model\Settings\GlobalSettings.cs:line 608
>    at PoGo.NecroBot.Logic.Model.Settings.GlobalSettings.Load(String path, Boolean boolSkipSave, Boolean validate) in c:\projects\necrobot2\PoGo.NecroBot.Logic\Model\Settings\GlobalSettings.cs:line 351
>    at PoGo.NecroBot.Logic.State.StateMachine.<>c__DisplayClass3_0.<Start>b__0(Object sender, FileSystemEventArgs e) in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:line 47
>    at System.IO.FileSystemWatcher.OnChanged(FileSystemEventArgs e)
>    at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(Int32 action, String name)
>    at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
>    at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

**Comment by seouljah760** [comment]
This actually happens all the time, since way before the forks. The update function is fickle at best. I recommend you back up your auth.json and config.json after every config change made by you. That way every release, you can just manually down load the latest build, and copy over your config and auth json files. You can turn off the update and update checking in the config.

That being said, i know thats not what you wanted to hear. but the core bot functions are taking precedence right now. The update function is more of a "want" than a "need" at the moment. I have yet to see any real update to the upgrade function in a while. 

While i can verify your bug finding, and it is quite annoying, i don't see it getting fixed any time soon.

**Comment by jjskuld** [comment]
This may have also been fixed by the new update changes. Please re-open if you still see this issue in 1.0.0.20
