### ISSUE TITLE
NecroBot2 GUI - Can't transfer/evolve/power up Pokemon 

### ISSUE THREAD

**Issue by 3nterprise** [Necrobot-Private/NecroBot#321]
In Pokemons inventory, when you select certain pokemon to Transfer/Evolve or Power Up, it wont do the certain action or the bot crashes itself.

**Comment by seouljah760** [comment]
So this isn't really a necrobot2 issue, this is a pokeease issue, which there is a fork for that has been kind of kept up with these devs. I understand since it is being distributed here. But i truly believe the GUI needs to have its own issues tracker.

That being said, I understand your frustration. The bot GUI is rough around the edges right now. And there are numerous fronts that being attacked on it, to include updates, captcha integration and improvements. Please bear with us, since this is two projects in one, with numerous other devs.

**Comment by ajns73** [comment]
@seouljah760 Perhaps the GUI should be taken out of releases for now then. When you release something "officially" you are inviting people to use and comment on it.

**Comment by xoira** [comment]
My same problem is also unresolved

NecroGUI UPGRADE -> YES and MAX button dose not work #266
https://github.com/Necrobot-Private/NecroBot/issues/266

Version:0.9.9.4-1.0.0.5 AND 1.0.0.15, 1.0.0.16
Windows Version: Windows10

**Comment by hardknoxni69a** [comment]
This Has Been Fixed In Latest  Electron GUI
