### ISSUE TITLE
Necrobot + PogoLocationFeeder

### ISSUE THREAD

**Issue by mahavidhan** [Necrobot-Private/NecroBot#464]
I remember I use to snipe pokemons while running PogoLocationFeeder simultaneously before. Is this function available in this latest version? Please let me know steps on how to activate/configure sniper settings.
Thanks

**Comment by samuraitruong** [comment]
we longer using that, since we has better internal feed source, 

data will come from my site http://www.mypogosnipers.com/

You can see autoconfig here - https://github.com/Necrobot-Private/NecroBot/wiki/Config-auto-sniper

and Manual - https://github.com/Necrobot-Private/NecroBot/wiki/Manual-snipe-config

@mahavidhan

**Comment by mahavidhan** [comment]
Wonderful !
Thanks !!
