### ISSUE TITLE
Problem with resolving Captcha

### ISSUE THREAD

**Issue by SLASHLogin** [Necrobot-Private/NecroBot#469]
Always when I turn on NecroBot I see
- Auto resolving captcha by using anti captcha service
but progress isn't ideal, 
After some time, when I deal with this problem resolving captcha by myself on my phone, I notice again attempt solving captcha but after some time I see also this:
 - Auto sniper detected a pokemon not in your pokedex:  Ditto. He will be snipped as priority!
And it's routine.

**Comment by junreygc** [comment]
There is a warning that legacy API triggers captcha. Auto-resolve feature is not configured properly by default or is not working at all so turn it off. As far as I know Ditto will not be sniped as Ditto because it always uses other Pokemons' form during encounter. My sniper tells me sniping Pidgey and CatchSuccess: Pidgey but when I open in phone it is Ditto not Pidgey.

**Comment by SLASHLogin** [comment]
Thanks I repair than with help discord chat.

**Comment by samuraitruong** [comment]
We still haven't add code to detect Ditto
