### ISSUE TITLE
How to snipe pokemon of a high level and how to write specific moves

### ISSUE THREAD

**Issue by mahavidhan** [Necrobot-Private/NecroBot#470]
Hello

I need a 90%+ Charizard having Wing Attack + Fire Blast OR Ember + Fire Blast preferably of 25+ Level. In such a scenario, How do I write it in config? There is no parameter/attribute to mention specific level.

  "SnipePokemonFilter": {
    "Charizard": {
      "SnipeIV": 90,
      "Moves": [Wing Attack + Fire Blast OR Ember + Fire Blast],
      "Operator": "and",
      "VerifiedOnly": false
    }

Please help

**Comment by junreygc** [comment]
You can't control the level of Pokemons you capture because it is relative to your Trainer's Level.
A Charizard in one location captured by a group of trainers will have a different level per trainer depending on the trainer levels. Only the IV which will remain the same for all the trainers.

For the MoveSets I can't get it to work, it says expecting array/null but got string.
Here is my example:
`  "SnipePokemonFilter": {`
  `    "Dragonite": {`
`      "SnipeIV": 100,`
`      "Moves": [`
`        "dragonBreathFast",`
`        "hyperBeam"`
`      ],`
`      "Operator": "and",`
`      "VerifiedOnly": true`
`    },`
