### ISSUE TITLE
Filter sniper sistem for optimize snipe

### ISSUE THREAD

**Issue by yandrake** [Necrobot-Private/NecroBot#472]
At this moment in msniper, when you snipe a pokemon, sometimes you get multiple same coords for the same pokemon. I dont mean exactly the same coords, I mean more or less the same coords but with more numbers. For example: Dragonite in 1.234,1.234 , and then it tries to snipe that dragonite again in: Dragonite in 1.23456, 1.23456.
I dont know if is there a way to filter those coords, and only use one of them. It seems like if there are more numbers in coords, there are more chances to find pokemon there, so mabe if msniper filter the coords with less numbers and keep the coords that are more accurate, it could be good. Mabe I am wrong with this idea but it could help improve the eficiency of the sniping.

**Comment by junreygc** [comment]
The GPS itself isn't accurate. You will not be teleport-ed to the exact coordinates. That is why you will have the more or less same coordinate entries in sniper. The filter you are suggesting will work on rares but not with the very common because there are times the spawns of like for example Pidgeys are very close to each other having more or less the same coordinates but there exactly more than one Pidgey on that small area. So I agree on this for the rare and the very rare only.

**Comment by samuraitruong** [comment]
we have 2 data, 1 from bot which is know as verified data, 1 from discord and map they are not accuracy until one of our bot catch 
.

I need more front-end filter to filter out those data, one we has verify, the unverified need to be removed from site, marked as enhancement.

**Comment by samuraitruong** [comment]
this been fix with recently update
