### ISSUE TITLE
from no problem to an constantly catch flee problem, what to do?

### ISSUE THREAD

**Issue by Albertus30** [Necrobot-Private/NecroBot#508]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you searched to see if there are other Open/Closed issues for the same issue? If so, comment on that issue instead.
2. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/7FWyWVp 
4. Always confirm that your issue is reproducible, with the config you provide below.

### Your config.json:
```
replace this text with the contents of your config.json

```

### (OPTIONAL) Your Log:
```
replace this text with only the "relative" portion of your log. (Remove unnessary lines)

```

### Other Information
(Attach zip files if needed.)

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by Albertus30** [comment]
![img_2302](https://cloud.githubusercontent.com/assets/25077285/21886584/c1591f0c-d8bc-11e6-8d90-e70ac65b9c19.JPG)

**Comment by Axeia** [comment]
Constant fleeing means you got soft-banned. Have you tweaked the settings to move faster or have you been teleporting large distances? That's two things that are likely to get you soft banned.

I think you're best off just waiting it out, and it should expire on its own? Just Google for Pokémon Go Softban.

Now some tips:

- If you select the the text in the image you took a photo off and rightclick it will be copied to your clipboard. 
You can then simply paste it on here, preferable between three backticks (this character) `` ` `` so it's in a code block.

- To take a screenshot on your PC instead of having to take a photo press the `prt scn` key on your keyboard. Press alt at the same time to take a screenshot of only the active window (`alt+prt scn`). Then paste it in for example Microsoft Paint and save it as a jpg or png).

**Comment by samuraitruong** [comment]
yeah, seem got softban

**Comment by Albertus30** [comment]
ai ok, thanks for info

**Comment by Albertus30** [comment]
Its working again :)
it was indeed a softban, my settings were high (200 / 300kxp / h) have been adjusted to a more secure setting now

**Comment by samuraitruong** [comment]
wow, how you get that setting 200k exp, ?
