### ISSUE TITLE
RPM Question of hash server

### ISSUE THREAD

**Issue by mahavidhan** [Necrobot-Private/NecroBot#561]
I am using necrobot2 with PokeFamer hash server API key of the lowest package. The Wiki page says, 5$ = 150 RPM is enough for 3+ instance of bot running at the same time. Two questons
1. What is the exact definition of 3+? I am having 5 accounts in the multibot config. Will there be an issue?
2. What happens when I go over 150 RPM?
3. How to know if I am over utilizing RPM?
4. Any chances of getting banned for overutilizing RPM?

**Comment by macinmn** [comment]
not a dev, but:

1) "3+" I believe means simultaneous, and I rarely see my usage go about 30, so I would say more like 5 but they didn't want to over-advertise and then have unhappy users I'm sure.  multibot in Necro configuration only runs active one at a time, unless you have multiple instances open all running at the same time.

2/3) when you go over, you get a message that says your request was limited

4) I suppose if you had a LOT of requests from Niantic PoGo server end up not eventually resolving and providing a response, this would be possible, but Necro seems to me that it retries with the Buddy hash server, and then eventually gets back with the proper response to the Niantic server.  In my opinion should be no different than if you had bad cell signal strength... *could* it be a means of detection? I suppose anything is possible but I really doubt it.  Just like you don't want to be caught, Niantic doesn't want to false-catch and ban potentially paying customers, or friends of potentially paying customer that might trash talk them.

**Comment by samuraitruong** [comment]
150 RPM is enought for 3 instance if depend on your config, you should check message to see how many request you have /min for your BOT. then if is <50 then ok for 3 bot

If you reach limit, your bot will very slow since it has to wait few sec to make 1 single request.

No ban at all with hash limit, just make your bot slow. But i think 3 instance for 5$/month is cheap since with multiple acc support you can run 3*5 = 15 acc.
