### ISSUE TITLE
Account ban and purchased key

### ISSUE THREAD

**Issue by mahavidhan** [Necrobot-Private/NecroBot#638]
I had four accounts, 1 ptc and 3 google. 1 google account if working but I am unable to login to 3 of those dummy accounts. The bot says credentials are invalid and device says unable to authenticate. Is this a ban? I had purchased one lowest 150 rpm key so is it possible to get banned using a purchased key? If not ban then how do get rid of the credentials error?
Please advice
Thanks

**Comment by xRpwn** [comment]
its a ban i got the same

**Comment by Axeia** [comment]
Same here, looks like a banwave has happened then.

**Comment by jokki89** [comment]
I've the same problem...but it was my main account...I can't log into it now since 5days.. And I had purchased a 500rpm key but I think it doesn't matter..but anyway, everyone told me that if you get banned you have to receive a mail from niantic that your account is banned. And I didn't get a mail like this until now.. so I sent a mail to niantic an now I await an answer from them and hope it's just an error..but I don't think so.. :/

**Comment by boscorelly** [comment]
a mate was banned a long time ago and he gots a mail from niantic "account terminated".

No mail, nothing.

**Comment by crwys123** [comment]
Banned here as well

**Comment by mahavidhan** [comment]
But the question remains unanswered ! I was botting normally without any greed. Is there still a chance to get banned even with a purchased key?

**Comment by mahavidhan** [comment]
@samuraitruong Can you please answer the above question? I wish to know if I should buy another key or be happy with the Legacy API

**Comment by xRpwn** [comment]
you dont need to buy other use the same

**Comment by mahavidhan** [comment]
That I know. What I need to know is that Is there still a chance of getting banned even after purchasing the key? If yes then there is no point buying it !

**Comment by boscorelly** [comment]
he is always closing issues/questions without answering... Stop doing that !

**Comment by crwys123** [comment]
Because this is a place to report bugs on necrobot. 
This isn't a bug, it's discussion not meant for here. 

mahavidhan

My guess is that the recent change in api is probably what caused the bans. I too bot occasionally and still got banned. All boys had to be updated when pokemon go was updated, and those who still played took the risk. So for the future I would check to make sure pokemon go wasn't updated and then run your bot. If it was updated I would wait until it's safe to bot again. Usually after a couple releases.
