### ISSUE TITLE
Pokestop

### ISSUE THREAD

**Issue by gatesjr** [Necrobot-Private/NecroBot#801]
had bot running all night and it only did 2 pokestops over and over and over i have about 20 pokestops in my area all together but it just walks to 2 they are 523m away from each other and skips all the others why is this

**Comment by hardknoxni69a** [comment]
the bot is going to go to the stop that is closest and ready to spin so if you have stops that take about 5 minutes apart from eachother while catching pokemon it might repeat the same stops if you speed up your bot or set a gpx path you will go to different stops

**Comment by gatesjr** [comment]
i did not set any path or anything like that and all i am doing is spinning stops no catching and no it is going back and forth between these 2 main stops and not spinning anything else

**Comment by gatesjr** [comment]
http://prntscr.com/e7hqvo, here is screenshot and that's all it is doing between those 2 stops

**Comment by hardknoxni69a** [comment]
Ya because the time it takes to travel between those stops they only go between those 2 because it's the closest stop that is available to spin I would recommend changing locations to somewhere else that has more stops or set up a gpx path and about pokemon do u have any pokemon spawns between there it appears you are in a very rural place
