### ISSUE TITLE
protobuff ?

### ISSUE THREAD

**Issue by evetaku** [Necrobot-Private/NecroBot#87]
1. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead. YES
2. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.YES VALID

Version:
Windows Version: windows 10 64bit
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): : protobuff ?

this's first fime im use Necrov2 v0.9.8.7, this's warning or something wrong with my config ? but im check in jsonlint.com is Valid JSON
![asdasd](https://cloud.githubusercontent.com/assets/6820983/18430927/c5ad87cc-7904-11e6-9e1f-cc145a9bef1f.png)

**Comment by mo0ojava** [comment]
This is from an unhandled exception in the FeroxRev login-procedure and is a known bug (that appeared just recently). If you wait a while after that message appears it will retry the login. More often than not it will succeed the second time and then everything continues as usual. I'm guessing this will be fixed until after the upcoming (and breaking) changes appears since it'll likely have to be remade then anyway.

**Comment by evetaku** [comment]
@mo0ojava 1 more where's we can get google api key ?
in here https://console.developers.google.com/apis ?

**Comment by iwean** [comment]
If you want a new google api.... get from this link:

https://developers.google.com/maps/documentation/directions/get-api-key?authuser=3

**Comment by evetaku** [comment]
oke thanks, but this bug is problem
@iwean  indo ?

**Comment by iwean** [comment]
Yup.... and you @evetaku ?

**Comment by mo0ojava** [comment]
Cooked up a quickfix for this. I'll make a PR once the debug-session has finished.
